# IMPORTANT
# Clone the themes to '~/.config/alacritty/' directory
# Repo: https://github.com/alacritty/alacritty-theme

import = [
#    "~/.config/alacritty/themes/themes/papercolor_dark.toml"
#    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
#    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.96

[window.padding]
x = 8
y = 8

[font]
size = 12.0

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Medium"

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMonoNerdFont"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Medium Italic"



