# IMPORTANT
# Clone the themes to '~/.config/alacritty/' directory
# Repo: https://github.com/alacritty/alacritty-theme

import = [
#    "~/.config/alacritty/themes/themes/papercolor_dark.toml"
#    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
#    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 1

[window.position]
x = 500
y = 220

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 100
lines = 30

[cursor]
style.shape = "Block"
thickness = 0.2

[font]
size = 11.0
[font.offset]
y = -2
[font.glyph_offset]
y = -2

[font.normal]
# family = "Hack"
# family = "MesloLGM Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Normal"

[font.bold]
# family = "Hack"
family = "JetBrainsMono Nerd Font"
style = "Bold"
