# IMPORTANT
# Clone the themes to '~/.config/alacritty/' directory
# Repo: https://github.com/alacritty/alacritty-theme

import = [
#    "~/.config/alacritty/themes/themes/papercolor_dark.toml"
#    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
#    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[shell]
#program = "/bin/bash"
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 1.0
title = "Alacritty"
dynamic_title = false

[window.position]
x = 500
y = 220

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 7
y = 7

[font]
size = 11

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
# family = "MesloLGM Nerd Font Mono"
# family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
# family = "MesloLGM Nerd Font Mono"
# family = "Hack Nerd Font Mono"
style = "Bold"

