# IMPORTANT
# Clone the themes to '~/.config/alacritty/' directory
# Repo: https://github.com/alacritty/alacritty-theme

import = [
#    "~/.config/alacritty/themes/themes/papercolor_dark.toml"
#    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
    "~/.config/alacritty/themes/themes/dracula_plus.toml"
#    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.99

[window.position]
x = 500
y = 220

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 8
y = 8

[font]
size = 12.0

[font.normal]
#family = "JetBrainsMonoNerdFont"
family = "MesloLGM Nerd Font Mono"
style = "Medium"

[font.bold]
#family = "JetBrainsMonoNerdFont"
family = "MesloLGM Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
#family = "JetBrainsMonoNerdFont"
family = "MesloLGM Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
#family = "JetBrainsMonoNerdFont"
family = "MesloLGM Nerd Font Mono"
style = "Medium Italic"

