#!/bin/bash

# prefix paths
PATH="/dir:$PATH"

# suffix paths
PATH="$PATH:/dir"

# tools
export SDKMAN_DIR="$HOME/.sdkman"
export NVM_DIR="$HOME/.nvm"
# machines
export GOOGLE="fazledyn@35.245.156.196"
