#!/bin/bash

# prefix paths
# PATH="/dir:$PATH"

# suffix paths
# PATH="$PATH:/dir"
PATH="$PATH:/opt/codeql"
PATH="$PATH:/opt/node/bin"
PATH="$PATH:/opt/maven/bin"
PATH="$PATH:$HOME/.local/bin"

# tools
export NVM_DIR="$HOME/.nvm"
export SDKMAN_DIR="$HOME/.sdkman"

# machines
export ZEUS="aahamed@zeus.cec.gmu.edu"
export EXOSPHERE="aahamed@129.174.189.8"
export HOPPER="aahamed@hopper.orc.gmu.edu"
